In [10]:
import numpy as np


arr = np.array([1, 2, 1, 1, 34, 2, 1, 2])

print(arr)

print(np.eye(4)[[0, 1, 0]])

[ 1  2  1  1 34  2  1  2]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [17]:
np.empty((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
total_layer_size = [10, 5, 5, 2]
batch_size = 8
hidden_layer = [np.empty((batch_size, layer)) for layer in total_layer_size]

In [20]:
hidden_layer[0].shape

(8, 10)

In [23]:
#60000 / 32
10000 / 32

312.5